/* Generated by tools/build_gallery.py – titles may be edited by hand. */
window.GALLERY = [
 {
  "id": "1hoor7s",
  "title": "Blossom Lane",
  "src": "images/web/1hoor7s.jpg",
  "thumb": "images/thumbs/1hoor7s.jpg",
  "w": 1920,
  "h": 1200
 },
 {
  "id": "22qa12m",
  "title": "Little Boat at Sea",
  "src": "images/web/22qa12m.jpg",
  "thumb": "images/thumbs/22qa12m.jpg",
  "w": 1920,
  "h": 1080
 },
 {
  "id": "comfyui-0021",
  "title": "Red Forest Temple",
  "src": "images/web/comfyui-0021.jpg",
  "thumb": "images/thumbs/comfyui-0021.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00290",
  "title": "Blue-Domed Palace",
  "src": "images/web/comfyui-00290.jpg",
  "thumb": "images/thumbs/comfyui-00290.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00294",
  "title": "Golden Spires",
  "src": "images/web/comfyui-00294.jpg",
  "thumb": "images/thumbs/comfyui-00294.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00316",
  "title": "Minarets in the Clouds",
  "src": "images/web/comfyui-00316.jpg",
  "thumb": "images/thumbs/comfyui-00316.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00319",
  "title": "Lake Palace",
  "src": "images/web/comfyui-00319.jpg",
  "thumb": "images/thumbs/comfyui-00319.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00320",
  "title": "Golden Dome Valley",
  "src": "images/web/comfyui-00320.jpg",
  "thumb": "images/thumbs/comfyui-00320.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00323",
  "title": "Turquoise Domes",
  "src": "images/web/comfyui-00323.jpg",
  "thumb": "images/thumbs/comfyui-00323.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00327",
  "title": "Magenta Garden Mosque",
  "src": "images/web/comfyui-00327.jpg",
  "thumb": "images/thumbs/comfyui-00327.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00328",
  "title": "Emerald Portal",
  "src": "images/web/comfyui-00328.jpg",
  "thumb": "images/thumbs/comfyui-00328.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00330",
  "title": "Palm Court",
  "src": "images/web/comfyui-00330.jpg",
  "thumb": "images/thumbs/comfyui-00330.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00333",
  "title": "Sapphire Mosque",
  "src": "images/web/comfyui-00333.jpg",
  "thumb": "images/thumbs/comfyui-00333.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00335",
  "title": "Twin Towers of Jade",
  "src": "images/web/comfyui-00335.jpg",
  "thumb": "images/thumbs/comfyui-00335.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00337",
  "title": "Tiled Archways",
  "src": "images/web/comfyui-00337.jpg",
  "thumb": "images/thumbs/comfyui-00337.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00339",
  "title": "Sunset Minaret",
  "src": "images/web/comfyui-00339.jpg",
  "thumb": "images/thumbs/comfyui-00339.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00342",
  "title": "Desert Blue Mosque",
  "src": "images/web/comfyui-00342.jpg",
  "thumb": "images/thumbs/comfyui-00342.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00344",
  "title": "Garden of Arches",
  "src": "images/web/comfyui-00344.jpg",
  "thumb": "images/thumbs/comfyui-00344.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00345",
  "title": "Carved Dome",
  "src": "images/web/comfyui-00345.jpg",
  "thumb": "images/thumbs/comfyui-00345.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00351",
  "title": "Blossom Temple",
  "src": "images/web/comfyui-00351.jpg",
  "thumb": "images/thumbs/comfyui-00351.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00352",
  "title": "Palm Sanctuary",
  "src": "images/web/comfyui-00352.jpg",
  "thumb": "images/thumbs/comfyui-00352.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00354",
  "title": "Pink Bloom Palace",
  "src": "images/web/comfyui-00354.jpg",
  "thumb": "images/thumbs/comfyui-00354.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00358",
  "title": "White Gate",
  "src": "images/web/comfyui-00358.jpg",
  "thumb": "images/thumbs/comfyui-00358.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00359",
  "title": "Green Moon Minarets",
  "src": "images/web/comfyui-00359.jpg",
  "thumb": "images/thumbs/comfyui-00359.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00361",
  "title": "Jungle Pavilion",
  "src": "images/web/comfyui-00361.jpg",
  "thumb": "images/thumbs/comfyui-00361.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00362",
  "title": "Golden Tile Mosque",
  "src": "images/web/comfyui-00362.jpg",
  "thumb": "images/thumbs/comfyui-00362.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00365",
  "title": "Obsidian Domes",
  "src": "images/web/comfyui-00365.jpg",
  "thumb": "images/thumbs/comfyui-00365.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00371",
  "title": "Storm Pagodas",
  "src": "images/web/comfyui-00371.jpg",
  "thumb": "images/thumbs/comfyui-00371.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00423",
  "title": "Bronze Cathedral",
  "src": "images/web/comfyui-00423.jpg",
  "thumb": "images/thumbs/comfyui-00423.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00425",
  "title": "White Pyramid",
  "src": "images/web/comfyui-00425.jpg",
  "thumb": "images/thumbs/comfyui-00425.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00426",
  "title": "Moonrise Citadel",
  "src": "images/web/comfyui-00426.jpg",
  "thumb": "images/thumbs/comfyui-00426.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00430",
  "title": "Pearl Domes",
  "src": "images/web/comfyui-00430.jpg",
  "thumb": "images/thumbs/comfyui-00430.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00431",
  "title": "Crimson Carpet Mosque",
  "src": "images/web/comfyui-00431.jpg",
  "thumb": "images/thumbs/comfyui-00431.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00432",
  "title": "Crescent Sky",
  "src": "images/web/comfyui-00432.jpg",
  "thumb": "images/thumbs/comfyui-00432.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00433",
  "title": "Tiered Golden Temple",
  "src": "images/web/comfyui-00433.jpg",
  "thumb": "images/thumbs/comfyui-00433.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00434",
  "title": "Rose Garden Shrine",
  "src": "images/web/comfyui-00434.jpg",
  "thumb": "images/thumbs/comfyui-00434.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00435",
  "title": "Many Domes",
  "src": "images/web/comfyui-00435.jpg",
  "thumb": "images/thumbs/comfyui-00435.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00436",
  "title": "Rose Courtyard",
  "src": "images/web/comfyui-00436.jpg",
  "thumb": "images/thumbs/comfyui-00436.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00438",
  "title": "Desert Pavilion",
  "src": "images/web/comfyui-00438.jpg",
  "thumb": "images/thumbs/comfyui-00438.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00489",
  "title": "Cyber Pagoda",
  "src": "images/web/comfyui-00489.jpg",
  "thumb": "images/thumbs/comfyui-00489.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00490",
  "title": "Dark Star Temple",
  "src": "images/web/comfyui-00490.jpg",
  "thumb": "images/thumbs/comfyui-00490.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00491",
  "title": "Stepped Temple",
  "src": "images/web/comfyui-00491.jpg",
  "thumb": "images/thumbs/comfyui-00491.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00494",
  "title": "Neon Spire",
  "src": "images/web/comfyui-00494.jpg",
  "thumb": "images/thumbs/comfyui-00494.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00495",
  "title": "Neon City",
  "src": "images/web/comfyui-00495.jpg",
  "thumb": "images/thumbs/comfyui-00495.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00498",
  "title": "Moonlit White Mosque",
  "src": "images/web/comfyui-00498.jpg",
  "thumb": "images/thumbs/comfyui-00498.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00499",
  "title": "Turquoise & Pink",
  "src": "images/web/comfyui-00499.jpg",
  "thumb": "images/thumbs/comfyui-00499.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00518",
  "title": "Golden Ruins",
  "src": "images/web/comfyui-00518.jpg",
  "thumb": "images/thumbs/comfyui-00518.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00519",
  "title": "Mossy Gold Palace",
  "src": "images/web/comfyui-00519.jpg",
  "thumb": "images/thumbs/comfyui-00519.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00525",
  "title": "Beacon Temple",
  "src": "images/web/comfyui-00525.jpg",
  "thumb": "images/thumbs/comfyui-00525.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00527",
  "title": "Moon Over Ruins",
  "src": "images/web/comfyui-00527.jpg",
  "thumb": "images/thumbs/comfyui-00527.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00531",
  "title": "Grey Pagoda",
  "src": "images/web/comfyui-00531.jpg",
  "thumb": "images/thumbs/comfyui-00531.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00532",
  "title": "Stone Dome at Night",
  "src": "images/web/comfyui-00532.jpg",
  "thumb": "images/thumbs/comfyui-00532.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00533",
  "title": "Moonlit Pagodas",
  "src": "images/web/comfyui-00533.jpg",
  "thumb": "images/thumbs/comfyui-00533.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00539",
  "title": "Blue Night Mosque",
  "src": "images/web/comfyui-00539.jpg",
  "thumb": "images/thumbs/comfyui-00539.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00541",
  "title": "Teal Evening",
  "src": "images/web/comfyui-00541.jpg",
  "thumb": "images/thumbs/comfyui-00541.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00549",
  "title": "Shadow Palace",
  "src": "images/web/comfyui-00549.jpg",
  "thumb": "images/thumbs/comfyui-00549.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00609",
  "title": "Colonnade at Dusk",
  "src": "images/web/comfyui-00609.jpg",
  "thumb": "images/thumbs/comfyui-00609.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00610",
  "title": "Pillared Hall",
  "src": "images/web/comfyui-00610.jpg",
  "thumb": "images/thumbs/comfyui-00610.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00612",
  "title": "Grand Interior",
  "src": "images/web/comfyui-00612.jpg",
  "thumb": "images/thumbs/comfyui-00612.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00614",
  "title": "Green-Domed Hall",
  "src": "images/web/comfyui-00614.jpg",
  "thumb": "images/thumbs/comfyui-00614.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00615",
  "title": "Hall of Columns",
  "src": "images/web/comfyui-00615.jpg",
  "thumb": "images/thumbs/comfyui-00615.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00618",
  "title": "Lantern Palace",
  "src": "images/web/comfyui-00618.jpg",
  "thumb": "images/thumbs/comfyui-00618.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00630",
  "title": "Fire-Lit Fortress",
  "src": "images/web/comfyui-00630.jpg",
  "thumb": "images/thumbs/comfyui-00630.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00650",
  "title": "Golden Dome Ruins",
  "src": "images/web/comfyui-00650.jpg",
  "thumb": "images/thumbs/comfyui-00650.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00654",
  "title": "Crimson Palace",
  "src": "images/web/comfyui-00654.jpg",
  "thumb": "images/thumbs/comfyui-00654.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00658",
  "title": "Azure Pagodas",
  "src": "images/web/comfyui-00658.jpg",
  "thumb": "images/thumbs/comfyui-00658.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00726",
  "title": "Ancient Colonnade",
  "src": "images/web/comfyui-00726.jpg",
  "thumb": "images/thumbs/comfyui-00726.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00741",
  "title": "Weathered Mosque",
  "src": "images/web/comfyui-00741.jpg",
  "thumb": "images/thumbs/comfyui-00741.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00779",
  "title": "Red Trees & Grey Temples",
  "src": "images/web/comfyui-00779.jpg",
  "thumb": "images/thumbs/comfyui-00779.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00780",
  "title": "Temple Valley",
  "src": "images/web/comfyui-00780.jpg",
  "thumb": "images/thumbs/comfyui-00780.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00783",
  "title": "Stone Tower",
  "src": "images/web/comfyui-00783.jpg",
  "thumb": "images/thumbs/comfyui-00783.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00786",
  "title": "Red Pagoda",
  "src": "images/web/comfyui-00786.jpg",
  "thumb": "images/thumbs/comfyui-00786.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "comfyui-00788",
  "title": "Autumn Citadel",
  "src": "images/web/comfyui-00788.jpg",
  "thumb": "images/thumbs/comfyui-00788.jpg",
  "w": 2048,
  "h": 1024
 },
 {
  "id": "img-20191105-181142",
  "title": "Sleepy Cat",
  "src": "images/web/img-20191105-181142.jpg",
  "thumb": "images/thumbs/img-20191105-181142.jpg",
  "w": 1536,
  "h": 2048
 },
 {
  "id": "anato-finnstark-zenyatta-overwatch-by-anatofinnstark-da4xtk4-1",
  "title": "Zenyatta (Anato Finnstark)",
  "src": "images/web/anato-finnstark-zenyatta-overwatch-by-anatofinnstark-da4xtk4-1.jpg",
  "thumb": "images/thumbs/anato-finnstark-zenyatta-overwatch-by-anatofinnstark-da4xtk4-1.jpg",
  "w": 1280,
  "h": 720
 },
 {
  "id": "wallhaven-72337",
  "title": "Owl",
  "src": "images/web/wallhaven-72337.jpg",
  "thumb": "images/thumbs/wallhaven-72337.jpg",
  "w": 1680,
  "h": 1050
 },
 {
  "id": "wallhaven-q2jgkd",
  "title": "Forest Steps",
  "src": "images/web/wallhaven-q2jgkd.jpg",
  "thumb": "images/thumbs/wallhaven-q2jgkd.jpg",
  "w": 2048,
  "h": 819
 },
 {
  "id": "wallhaven-z8zgqw",
  "title": "Mountain Meadow",
  "src": "images/web/wallhaven-z8zgqw.jpg",
  "thumb": "images/thumbs/wallhaven-z8zgqw.jpg",
  "w": 1920,
  "h": 1080
 },
 {
  "id": "zqtdygy",
  "title": "Content Fox",
  "src": "images/web/zqtdygy.jpg",
  "thumb": "images/thumbs/zqtdygy.jpg",
  "w": 1920,
  "h": 1080
 }
];
