#!/usr/bin/env python3
"""
Build the picture gallery from the images/ folder.

For every image in images/ this writes
  images/web/<id>.jpg     a web-sized copy (longest side 2048 px) used for painting
  images/thumbs/<id>.jpg  a small gallery thumbnail
and regenerates js/gallery-data.js, the list the game reads.

Titles you edit by hand in js/gallery-data.js are kept on the next run.

Usage:  pip install pillow
        python3 tools/build_gallery.py
"""
import json
import re
import sys
from pathlib import Path

try:
    from PIL import Image, ImageOps
except ImportError:
    sys.exit('Pillow is required:  pip install pillow')

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / 'images'
WEB = SRC / 'web'
THUMBS = SRC / 'thumbs'
DATA = ROOT / 'js' / 'gallery-data.js'
EXTS = {'.jpg', '.jpeg', '.png', '.webp', '.bmp', '.gif'}
WEB_MAX = 2048
THUMB_W = 480


def slug(stem):
    s = re.sub(r'[^a-zA-Z0-9]+', '-', stem).strip('-').lower()
    return s or 'image'


def default_title(stem):
    m = re.fullmatch(r'ComfyUI_0*(\d+)_?', stem)
    if m:
        return f'Artwork {m.group(1)}'
    words = [w for w in re.split(r'[\s_\-]+', stem) if w]
    # drop camera-style and hash-like chunks
    words = [w for w in words if not re.fullmatch(r'(img|dsc|pxl)?\d{4,}', w, re.I)
             and not (re.search(r'\d', w) and re.search(r'[a-zA-Z]', w) and len(w) >= 6)]
    title = ' '.join(w.capitalize() for w in words[:4])
    return title or 'Picture'


def load_existing():
    if not DATA.exists():
        return {}
    text = DATA.read_text(encoding='utf-8')
    m = re.search(r'=\s*(\[.*\])\s*;', text, re.S)
    if not m:
        return {}
    try:
        return {e['id']: e for e in json.loads(m.group(1))}
    except (ValueError, KeyError):
        return {}


def flatten(im):
    im = ImageOps.exif_transpose(im)
    if im.mode in ('RGBA', 'LA', 'P'):
        im = im.convert('RGBA')
        bg = Image.new('RGB', im.size, (255, 255, 255))
        bg.paste(im, mask=im.split()[-1])
        return bg
    return im.convert('RGB')


def main():
    WEB.mkdir(parents=True, exist_ok=True)
    THUMBS.mkdir(parents=True, exist_ok=True)
    existing = load_existing()
    files = sorted(p for p in SRC.iterdir() if p.is_file() and p.suffix.lower() in EXTS)
    entries, used = [], set()
    for i, path in enumerate(files, 1):
        base = slug(path.stem)
        pid, n = base, 2
        while pid in used:
            pid, n = f'{base}-{n}', n + 1
        used.add(pid)
        web, thumb = WEB / f'{pid}.jpg', THUMBS / f'{pid}.jpg'
        fresh = all(p.exists() and p.stat().st_mtime >= path.stat().st_mtime for p in (web, thumb))
        if fresh:
            with Image.open(web) as im:
                w, h = im.size
        else:
            with Image.open(path) as src:
                im = flatten(src)
            im.thumbnail((WEB_MAX, WEB_MAX), Image.LANCZOS)
            im.save(web, 'JPEG', quality=88, optimize=True, progressive=True)
            w, h = im.size
            t = im.copy()
            t.thumbnail((THUMB_W, THUMB_W), Image.LANCZOS)
            t.save(thumb, 'JPEG', quality=80, optimize=True, progressive=True)
        old = existing.get(pid, {})
        entries.append({
            'id': pid,
            'title': old.get('title') or default_title(path.stem),
            'src': f'images/web/{pid}.jpg',
            'thumb': f'images/thumbs/{pid}.jpg',
            'w': w, 'h': h,
        })
        print(f'[{i}/{len(files)}] {path.name} -> {pid} ({w}x{h}){"" if not fresh else " (cached)"}')

    # remove outputs whose source image was deleted
    keep = {e['id'] for e in entries}
    for folder in (WEB, THUMBS):
        for p in folder.glob('*.jpg'):
            if p.stem not in keep:
                p.unlink()

    body = json.dumps(entries, indent=1, ensure_ascii=False)
    DATA.write_text('/* Generated by tools/build_gallery.py – titles may be edited by hand. */\n'
                    f'window.GALLERY = {body};\n', encoding='utf-8')
    print(f'Wrote {DATA.relative_to(ROOT)} with {len(entries)} pictures')


if __name__ == '__main__':
    main()
